image:
  path: "/deps-platform/deps-generic-unifier-plugin"
resources:

generic_unifier_plugin_settings:
  ENV: insurance
  VERIFY_SSL: 'false'
  OBJECT_STORAGE_TYPE: aws
  S3_BUCKET_NAME: bucket_name
  S3_ENDPOINT_URL: https://s3.us-east-1.amazonaws.com

csi:
  vault_namespace: 'k8s-ins'
  roleName: 'k8s-ins'
  vaultKubernetesMountPath: 'kubernetes-ins'

service_account:
  serviceAccountName: 'deps-insurance'

