image:
  path: "/deps-platform/deps-generic-unifier-plugin"
resources:

generic_unifier_plugin_settings:
  ENV: ds
  VERIFY_SSL: 'false'

csi:
  vault_namespace: 'k8s-ds'
  roleName: 'k8s-ds'
  vaultKubernetesMountPath: 'kubernetes-ds'

service_account:
  serviceAccountName: 'deps-ds'

