image:
  path: "/deps-presale-x01/deps-generic-unifier-plugin"
  pullPolicy: Always
resources:

generic_unifier_plugin_settings:
  ENV: presale
  VERIFY_SSL: 'false'

csi:
  vault_namespace: 'k8s-presale'
  roleName: 'k8s-presale'
  vaultKubernetesMountPath: 'kubernetes-presale'

service_account:
  serviceAccountName: 'deps-presale'


